# Generated by Django 5.0.6 on 2024-06-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sivista_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('usename', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
