# Generated by Django 5.0.6 on 2024-06-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sivista_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Usename', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=200)),
                ('Is_active', models.BooleanField(default=False)),
                ('Is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.DeleteModel(
            name='Sivista_User',
        ),
    ]
