# Generated by Django 5.0.6 on 2024-06-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_sivista_users_delete_sivista_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sivista_Users',
            new_name='User',
        ),
    ]
