# Generated by Django 5.0.6 on 2024-06-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_sivista_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Usename',
            new_name='Username',
        ),
    ]
