# Generated by Django 5.0.6 on 2024-07-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Uname',
        ),
    ]
