# Generated by Django 5.0.6 on 2024-07-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_rename_name_user_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Uname',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
